"""gen_pullon_l3_patterns.py — 自動 generate PullOn 五階反推 patterns 檔

從 m7_report 抽 PullOn 真實 (L1, L2, L3) 三元組統計，
配 bible 五階字典的圖片連結，產出 markdown 給 VLM prompt 用。

輸出：data/pullon_l1_l2_l3_patterns.md

每個 L3 含：
  - 占該 (L1, L2) 的百分比
  - bible 圖片連結（97% 有）
  - 簡短視覺描述（從 L3 名稱推導）

用法：
  python scripts\\gen_pullon_l3_patterns.py
"""
from __future__ import annotations
import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DL = ROOT.parent / "stytrix-pipeline-Download0504"
BIBLE = ROOT.parent / "五階層展開項目_20260402.xlsx"
OUT = ROOT / "data" / "pullon_l1_l2_l3_patterns.md"


def load_bible_chain_images():
    """{(L1, L2, L3) → image_url}"""
    if not BIBLE.exists():
        return {}
    import pandas as pd
    df = pd.read_excel(BIBLE, sheet_name="工作表1", engine="calamine")
    images = {}
    for _, row in df.iterrows():
        l1 = str(row.get("部位") or "").lstrip("*").strip()
        l2 = str(row.get("零件") or "").lstrip("*").strip()
        l3 = str(row.get("形狀設計") or "").lstrip("*").strip()
        img = str(row.get("圖片連結") or "").strip()
        if l1 and l2 and l3 and "FiveLevel_MethodDescribe" in img:
            images.setdefault((l1, l2, l3), img)
    return images


def load_pullon_stats():
    """從 m7_report 抽 PullOn 的 (L1, L2, L3) 統計"""
    m7 = DL / "data" / "ingest" / "metadata" / "m7_report.jsonl"
    stats = defaultdict(lambda: defaultdict(Counter))
    for line in open(m7, encoding="utf-8"):
        try:
            r = json.loads(line)
        except Exception:
            continue
        if "Pull On" not in (r.get("item") or ""):
            continue
        for s in r.get("five_level_detail", []):
            l1 = (s.get("category") or "").strip()
            l2 = (s.get("part") or "").strip().lstrip("*").strip()
            l3 = (s.get("shape_design") or "").strip().lstrip("*").strip()
            if l1 and l2 and l3:
                stats[l1][l2][l3] += 1
    return stats


# PullOn 主要 L1 + 簡短描述
PULLON_L1_DESCS = {
    "腰頭": "WB",
    "褲合身": "PS",
    "褲口": "LO",
    "口袋": "PK",
    "繩類": "DC",
    "褶": "PD",
    "釦鎖": "BS",
    "剪接線_下身類": "SB",
    "襬叉": "BP",
    "前立": "FY",
    "袋蓋": "FP",
    "帶絆": "LP",
    "拉鍊": "ZP",
}


def main():
    print("[1] 載入 bible (L1,L2,L3) → image lookup")
    images = load_bible_chain_images()
    print(f"    {len(images)} chains 有圖片連結")

    print("[2] 從 m7 抽 PullOn (L1,L2,L3) 統計")
    stats = load_pullon_stats()

    out_lines = []
    out_lines.append("# PullOn 五階反推 Patterns (含 L3 視覺特徵)\n\n")
    out_lines.append("> 從 m7_report 1180 PullOn EIDH × bible 五階字典反推\n")
    out_lines.append("> 用途：VLM 不只判 L1/L2，還要識別具體 L3 形狀變體\n")
    out_lines.append("> 自動 generated by `gen_pullon_l3_patterns.py`\n\n")
    out_lines.append("---\n\n")

    out_lines.append("## VLM 判斷流程\n\n")
    out_lines.append("```\n")
    out_lines.append("For each candidate L1:\n")
    out_lines.append("  1. 看下方 PullOn 該 L1 的 L2 候選\n")
    out_lines.append("  2. 我能看到任一具體 L2 pattern 嗎？\n")
    out_lines.append("  3. 看到 → 進一步判斷 L3 變體（有 bible 圖可對照）\n")
    out_lines.append("  4. 在 visual_description 寫『偵測到 L3=XXX』\n")
    out_lines.append("  5. 看不到 L2 → 不列該 L1\n")
    out_lines.append("```\n\n")
    out_lines.append("---\n\n")

    n_l1 = n_l2 = n_l3 = 0
    n_l3_with_img = 0

    # 依 PULLON_L1_DESCS 順序輸出
    for l1_zh, l1_code in PULLON_L1_DESCS.items():
        if l1_zh not in stats:
            continue
        l2_dict = stats[l1_zh]
        l1_total = sum(sum(c.values()) for c in l2_dict.values())
        n_l1 += 1

        out_lines.append(f"## {l1_code} {l1_zh}  (PullOn 總 {l1_total:,} steps)\n\n")

        # 取占比 ≥1% 的 L2
        l2_sorted = sorted(l2_dict.items(), key=lambda x: -sum(x[1].values()))
        for l2, l3_cnt in l2_sorted:
            l2_total = sum(l3_cnt.values())
            l2_pct = l2_total / l1_total * 100
            if l2_pct < 0.5:  # 小於 0.5% 跳過
                continue
            n_l2 += 1
            out_lines.append(f"### L2: {l2}  ({l2_total:,} steps, {l2_pct:.1f}% of {l1_code})\n\n")

            # 取占比 ≥3% 的 L3
            l3_sorted = l3_cnt.most_common(8)
            l3_total_pct = 0
            for l3, n in l3_sorted:
                l3_pct = n / l2_total * 100
                if l3_pct < 1:  # 小於 1% 跳過
                    continue
                n_l3 += 1
                l3_total_pct += l3_pct
                # 找對應圖片
                img = images.get((l1_zh, l2, l3))
                if img:
                    n_l3_with_img += 1
                # 從圖片 path 抽 L3 code（如 WB_001_a03_001.png → WB_001_a03）
                l3_code = ""
                if img:
                    fname = img.rsplit("\\", 1)[-1].rsplit("/", 1)[-1]
                    parts = fname.replace(".png", "").split("_")
                    if len(parts) >= 3:
                        l3_code = "_".join(parts[:3])

                img_marker = "🖼️" if img else "🚫"
                code_str = f" [{l3_code}]" if l3_code else ""
                out_lines.append(f"- **{l3}**{code_str} — {l3_pct:.1f}% ({n}) {img_marker}\n")

            out_lines.append(f"\n*  以上 top L3 占 {l3_total_pct:.0f}%*\n\n")

        out_lines.append("---\n\n")

    # Footer
    out_lines.append(f"\n## 統計摘要\n\n")
    out_lines.append(f"- L1 涵蓋: **{n_l1}** 個（PullOn 主要）\n")
    out_lines.append(f"- L2 涵蓋: **{n_l2}** 個\n")
    out_lines.append(f"- L3 涵蓋: **{n_l3}** 個\n")
    out_lines.append(f"- L3 有圖片連結: **{n_l3_with_img}/{n_l3}** ({n_l3_with_img/max(n_l3,1)*100:.0f}%)\n")
    out_lines.append(f"\n圖片路徑: `\\\\192.168.1.39\\mtm\\Images\\FiveLevel_MethodDescribe\\{{L1}}_{{NNN}}_{{a##}}_{{NNN}}.png`\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(out_lines), encoding="utf-8")

    print(f"\n[output] {OUT}")
    print(f"  {n_l1} L1 / {n_l2} L2 / {n_l3} L3")
    print(f"  圖片連結: {n_l3_with_img}/{n_l3} ({n_l3_with_img/max(n_l3,1)*100:.0f}%)")


if __name__ == "__main__":
    main()
