#!/usr/bin/env python3
"""audit_metadata.py — 掃 data/source/ + data/runtime/ JSON 的 lineage 三件套 metadata coverage
2026-05-16 P1 落地

Standard metadata schema (frontmatter):
  _description    : 1-2 sentence what this file is (required)
  _consumer       : list / dict of consumers (paths or names) (required)
  _source         : 資料來源 (xlsx / 業務知識 / generated by X) (required, but _generator may substitute)
  _generator      : derived 時必填 — 哪支 script 產出 (required for derived)
  _generated_at   : ISO timestamp (required)
  _sot            : SOT 標記 (optional, 只有 SOT 檔有)
  _version        : 檔格式版本 (optional)

兩種 metadata 位置:
  (a) Inline   — JSON 頂層加 _-prefix 欄位。適合 top-level 是 structured dict (version/created/...) 的檔
  (b) Sidecar  — <name>.meta.json 平行檔。適合 top-level keys 是 record IDs (design_id / POM code / bucket) 的檔

用法:
  # 純掃 (default)
  python scripts/core/audit_metadata.py
  python scripts/core/audit_metadata.py --json    # 出 JSON 報告而非 markdown

  # CI gate (檢測到 🔴 zero-metadata 直接 exit 1)
  python scripts/core/audit_metadata.py --strict

  # 範圍
  python scripts/core/audit_metadata.py --dir data/runtime  # 只掃單一目錄
"""
import argparse
import json
import sys
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parent.parent.parent
SCAN_DIRS = [ROOT / "data" / "source", ROOT / "data" / "runtime", ROOT / "path2_universal"]

REQUIRED_INLINE = ["_description", "_consumer", "_source", "_generated_at"]
REQUIRED_INLINE_ANY_OF = [["_source", "_generator"]]
OPTIONAL = ["_sot", "_version", "_generator"]

ALIAS_FIELDS = {
    "_description": ["_description", "description", "note", "_note"],
    "_consumer": ["_consumer", "consumer", "consumers"],
    "_source": ["_source", "source", "_authority", "_authoriy", "data_source", "sources"],
    "_generator": ["_generator", "generator", "built_from", "_built_from"],
    "_generated_at": ["_generated_at", "generated_at", "_updated", "updated", "created", "_created"],
    "_sot": ["_sot", "_sot_note"],
    "_version": ["_version", "version"],
}


def find_field(data: dict, canonical: str) -> str | None:
    if not isinstance(data, dict):
        return None
    aliases = ALIAS_FIELDS.get(canonical, [canonical])
    for alias in aliases:
        if alias in data:
            return alias
    return None


def find_metadata_block(data: dict) -> dict | None:
    if not isinstance(data, dict):
        return None
    for k in ("_meta", "_metadata"):
        if k in data and isinstance(data[k], dict):
            return data[k]
    return None


def audit_one(path: Path) -> dict:
    result = {
        "path": str(path.relative_to(ROOT)) if path.is_relative_to(ROOT) else str(path),
        "size_bytes": path.stat().st_size,
        "status": "?",
        "missing": [],
        "present": [],
        "has_sidecar": False,
        "metadata_location": None,
        "note": "",
    }

    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:
        result["status"] = "❌ PARSE ERROR"
        result["note"] = f"JSON parse fail: {e}"
        return result

    if not isinstance(data, dict):
        result["status"] = "🟡 NON-DICT TOP"
        result["note"] = f"Top-level is {type(data).__name__}, can't inline metadata"
        sidecar = path.parent / f"{path.stem}.meta.json"
        if sidecar.exists():
            result["has_sidecar"] = True
            result["metadata_location"] = "sidecar"
            result["status"] = "✅ SIDECAR"
        return result

    sample_keys = list(data.keys())[:10] if data else []
    has_underscore_metadata = any(k.startswith("_") for k in sample_keys)
    has_structured_top = any(k in data for k in ("version", "created", "description", "stats", "sources", "tier_rules", "method"))
    is_record_flat = not has_underscore_metadata and not has_structured_top

    sources_to_search = [data]
    meta_block = find_metadata_block(data)
    if meta_block:
        sources_to_search.append(meta_block)

    found = {}
    for canonical in REQUIRED_INLINE + OPTIONAL:
        for src in sources_to_search:
            actual = find_field(src, canonical)
            if actual:
                found[canonical] = actual
                break

    sidecar = path.parent / f"{path.stem}.meta.json"
    if sidecar.exists():
        result["has_sidecar"] = True
        try:
            sidecar_data = json.loads(sidecar.read_text(encoding="utf-8"))
            for canonical in REQUIRED_INLINE + OPTIONAL:
                if canonical not in found:
                    actual = find_field(sidecar_data, canonical)
                    if actual:
                        found[canonical] = f"sidecar.{actual}"
        except Exception:
            pass

    missing_required = [f for f in REQUIRED_INLINE if f not in found]
    present = list(found.keys())

    result["present"] = present
    result["missing"] = missing_required

    if not missing_required:
        result["status"] = "🟢 FULL"
        result["metadata_location"] = "sidecar" if result["has_sidecar"] else "inline"
    elif len(present) >= 2:
        result["status"] = "🟡 PARTIAL"
        result["metadata_location"] = "sidecar" if result["has_sidecar"] else "inline"
    elif len(present) >= 1:
        result["status"] = "🟠 MINIMAL"
        result["metadata_location"] = "inline"
    else:
        if is_record_flat:
            result["status"] = "🔴 ZERO (need sidecar)"
            result["note"] = "record-flat top (keys = IDs), 用 sidecar .meta.json"
        else:
            result["status"] = "🔴 ZERO"
        result["metadata_location"] = "none"

    return result


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", help="只掃單一目錄")
    ap.add_argument("--json", action="store_true", help="輸出 JSON 報告")
    ap.add_argument("--strict", action="store_true", help="🔴 zero-metadata → exit 1")
    args = ap.parse_args()

    scan_dirs = SCAN_DIRS if not args.dir else [ROOT / args.dir]

    all_results = []
    for d in scan_dirs:
        if not d.exists():
            continue
        for f in sorted(d.glob("*.json")):
            if f.name.endswith(".meta.json"):
                continue
            all_results.append(audit_one(f))

    by_status = {}
    for r in all_results:
        by_status.setdefault(r["status"], []).append(r)

    if args.json:
        print(json.dumps({
            "scan_at": datetime.utcnow().isoformat() + "Z",
            "n_files": len(all_results),
            "by_status": {k: len(v) for k, v in by_status.items()},
            "results": all_results,
        }, ensure_ascii=False, indent=2))
    else:
        print(f"# Metadata Audit — {datetime.utcnow().isoformat()}Z")
        print(f"\nScanned {len(all_results)} JSON files in: {', '.join(str(d.relative_to(ROOT)) for d in scan_dirs)}")
        print(f"\n## Summary")
        for status, items in sorted(by_status.items()):
            print(f"  {status:30s} {len(items):3d} files")

        print(f"\n## Detail")
        for status, items in sorted(by_status.items()):
            print(f"\n### {status}")
            for r in items:
                size_kb = r["size_bytes"] // 1024
                miss_str = f"missing: {', '.join(r['missing'])}" if r["missing"] else ""
                pres_str = f"present: {', '.join(r['present'][:5])}" if r["present"] else ""
                loc = r["metadata_location"] or "none"
                note = f"  ({r['note']})" if r["note"] else ""
                print(f"  - `{r['path']}` ({size_kb} KB, location={loc}){note}")
                if r["present"]:
                    print(f"      {pres_str}")
                if r["missing"]:
                    print(f"      ⚠ {miss_str}")

    if args.strict:
        zero_count = sum(1 for r in all_results if "🔴" in r["status"] or "❌" in r["status"])
        if zero_count > 0:
            sys.stderr.write(f"\n[STRICT] {zero_count} files have 🔴 ZERO or PARSE ERROR metadata. Fail.\n")
            sys.exit(1)
    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
